url: "https://justinxhale.github.io"
baseurl: "/reflog-site"

title: "RefLog"
description: "The modern referee's match companion - mobile-first rugby referee logging app."

markdown: kramdown
permalink: pretty